-- Add missing rut column to companies table
ALTER TABLE companies ADD COLUMN IF NOT EXISTS rut VARCHAR(20);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS tax_id VARCHAR(50);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS size VARCHAR(20);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS specialty VARCHAR(20);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS seismic_zone VARCHAR(10);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS region_code VARCHAR(10);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS library_seeded BOOLEAN DEFAULT FALSE;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS seeded_at TIMESTAMPTZ;